name: Daily AI Concepts Email

on:
  schedule:
    # Runs every day at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-daily-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run daily AI email script
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          python src/main.py
      
      - name: Commit updated concepts list
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -f data/sent_concepts.json ]; then
            git add data/sent_concepts.json
            git diff --quiet && git diff --staged --quiet || (git commit -m "📝 Update sent concepts list [skip ci]" && git push)
          fi
